# Generated by Django 5.0.1 on 2025-06-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramusers',
            options={'verbose_name': 'Telegram-пользователь', 'verbose_name_plural': 'Telegram-пользователи'},
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='chat_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='employee_status',
            field=models.CharField(blank=True, choices=[('manager', 'Менеджер'), ('employee', 'Сотрудник')], max_length=10, null=True, verbose_name='Должность сотрудника'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта (lat)'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='location_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота (lng)'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='telegram_users/photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='status',
            field=models.CharField(choices=[('customer', 'Клиент'), ('employee', 'Сотрудник')], default='customer', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Юзернейм'),
        ),
    ]
