# Generated by Django 5.0.1 on 2025-06-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_alter_telegramusers_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramusers',
            name='employee_status',
        ),
        migrations.AddField(
            model_name='telegramusers',
            name='employee_role',
            field=models.CharField(blank=True, choices=[('manager', 'Менеджер'), ('employee', 'Сотрудник')], max_length=10, null=True, verbose_name='Роль сотрудника'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='location_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='telegram_users/photos/', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
    ]
