# Generated by Django 5.0.1 on 2025-06-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0004_telegramusers_favourite_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusers',
            name='fine',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='telegramusers',
            name='point',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
