# Generated by Django 5.0.1 on 2025-06-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0005_telegramusers_fine_telegramusers_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramusers',
            name='employee_role',
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='status',
            field=models.CharField(choices=[('customer', 'Клиент'), ('employee', 'Сотрудник'), ('manager', 'Менеджер')], default='customer', max_length=10, verbose_name='Статус'),
        ),
    ]
