# Generated by Django 5.0.1 on 2025-06-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0006_remove_telegramusers_employee_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='fine',
            field=models.IntegerField(blank=True, default=0, verbose_name='Штраф'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='point',
            field=models.IntegerField(blank=True, default=0, verbose_name='Награда'),
        ),
    ]
