# Generated by Django 5.0.1 on 2025-08-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0007_alter_telegramusers_fine_alter_telegramusers_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='status',
            field=models.CharField(choices=[('user', 'Пользователь'), ('customer', 'Клиент'), ('employee', 'Сотрудник'), ('manager', 'Менеджер')], default='user', max_length=10, verbose_name='Статус'),
        ),
    ]
