# Generated by Django 5.0.1 on 2025-08-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0008_alter_telegramusers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='status',
            field=models.CharField(choices=[('user', 'Пользователь'), ('customer', 'Seller'), ('employee', 'Сотрудник'), ('manager', 'Менеджер')], default='user', max_length=10, verbose_name='Статус'),
        ),
    ]
