# Generated by Django 5.0.1 on 2025-06-21 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_users', '0005_telegramusers_fine_telegramusers_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('deadline', models.DateField(verbose_name='Крайний срок')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('reward', models.IntegerField(default=0, verbose_name='Награда (баллы)')),
                ('penalty', models.IntegerField(default=0, verbose_name='Штраф (баллы)')),
                ('status', models.CharField(choices=[('in_progress', '🟠 В процессе'), ('late', '🔴 Просрочен')], default='in_pogress', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='telegram_users.telegramusers', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
    ]
