# Generated by Django 5.0.1 on 2025-06-24 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_companies_phone_number_companies_group_id'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='companies.companies', verbose_name='Компания'),
            preserve_default=False,
        ),
    ]
