# Generated by Django 5.0.1 on 2025-06-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', '🟠 В процессе'), ('late', '🔴 Просрочен'), ('done', 'Завершено')], default='in_pogress', max_length=20, verbose_name='Статус'),
        ),
    ]
