# Generated by Django 5.0.1 on 2025-07-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', '🟠 В процессе'), ('late', '🔴 Просрочен'), ('done', 'Завершено')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
    ]
