# Generated by Django 5.0.1 on 2025-06-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('telegram_users', '0003_remove_telegramusers_employee_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='worked_companies', to='telegram_users.telegramusers', verbose_name='Сотрудники'),
        ),
        migrations.AddField(
            model_name='companies',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_companies', to='telegram_users.telegramusers', verbose_name='Менеджеры'),
        ),
    ]
