# Generated by Django 5.0.1 on 2025-06-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companies_employees_companies_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='companies',
            name='group_id',
            field=models.CharField(default='-12344321', max_length=50, verbose_name='Групповой идентификатор'),
            preserve_default=False,
        ),
    ]
