# Generated by Django 5.0.1 on 2025-06-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_companies_phone_number_companies_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='link',
            field=models.CharField(blank=True, null=True, verbose_name='Линк'),
        ),
    ]
