# Generated by Django 5.0.1 on 2025-07-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companies_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='group_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Групповой идентификатор'),
        ),
    ]
