# Generated by Django 5.0.1 on 2025-07-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_companies_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='ball',
            field=models.IntegerField(default=0, verbose_name='Счет'),
        ),
    ]
