# Generated by Django 5.0.1 on 2025-07-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companies_ball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='ball',
            field=models.IntegerField(default=0, verbose_name='Балл'),
        ),
    ]
