# Generated by Django 5.0.1 on 2025-08-03 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('telegram_users', '0008_alter_telegramusers_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Число')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cards', verbose_name='Карта')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_baskets', to='telegram_users.telegramusers', verbose_name='Продавец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_baskets', to='telegram_users.telegramusers', verbose_name='Telegram-пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'ordering': ['-user__id'],
            },
        ),
    ]
