# Generated by Django 5.0.1 on 2025-06-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='description',
        ),
    ]
