# Generated by Django 5.0.1 on 2025-07-16 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_users', '0007_alter_telegramusers_fine_alter_telegramusers_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=255, verbose_name='Имя должника')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма долга (сум)')),
                ('deadline', models.DateField(verbose_name='Срок возврата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='telegram_users.telegramusers', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
                'ordering': ['deadline'],
            },
        ),
    ]
