# Generated by Django 5.0.1 on 2025-07-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='price',
            field=models.FloatField(default=12.9),
            preserve_default=False,
        ),
    ]
