# Generated by Django 5.0.1 on 2025-07-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0003_alter_debt_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.IntegerField(verbose_name='Сумма долга (сум)'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='price',
            field=models.IntegerField(),
        ),
    ]
